version: '2.2'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.10.7-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
#    volumes:
#        - $PWD/docker-data/rabbitmq/data/:/var/lib/rabbitmq
#        - $PWD/docker-data/rabbitmq/log/:/var/log/rabbitmq
