version: '2.2'

services:
  rabbitmq:
    container_name: aleph-p2p-demo-rabbitmq
    restart: always
    image: rabbitmq:3.10.7-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - p2p-internal

  p2p-service:
    container_name: aleph-p2p-demo-service
    restart: always
    image: alephim/p2p-service:latest
    depends_on:
      - rabbitmq
    volumes:
      - ./sample-config.yml:/etc/p2p-service/config.yml
      - ./sample-key.bin:/etc/p2p-service/node-secret.pkcs8.der
    environment:
      RUST_LOG: info
    ports:
      - "4025:4025"
      - "4030:4030"
    command:
      - "--config"
      - "/etc/p2p-service/config.yml"
      - "--private-key-file"
      - "/etc/p2p-service/node-secret.pkcs8.der"
    networks:
      - p2p-internal

networks:
  p2p-internal:
