version: '2.2'

services:
  p2p-service:
    container_name: aleph-p2p-demo-service
    restart: always
    image: alephim/p2p-service:latest
    volumes:
      - ./sample-config.yml:/etc/p2p-service/config.yml
      - ./sample-key.bin:/etc/p2p-service/node-secret.pkcs8.der
    environment:
      RUST_LOG: info
    ports:
      - "4025:4025"
      - "127.0.0.1:4030:4030"
      - "127.0.0.1:4040:4040"
    command:
      - "--config"
      - "/etc/p2p-service/config.yml"
      - "--private-key-file"
      - "/etc/p2p-service/node-secret.pkcs8.der"
